### ISSUE TITLE
Requesting a screenshot

### ISSUE THREAD

**Issue by chrizator** [chrizator/netattack2#1]
![abc](https://cloud.githubusercontent.com/assets/26607154/25682907/7bccde58-3049-11e7-9e35-76ef52fd647b.png)

**Comment by ahmedkamal00** [comment]
i have all requirements but it doesnot work ?!

**Comment by chrizator** [comment]
Hello, it was my fault, I edited the README.md
You need to install nmap for python, not just nmap

apt-get install nmap-python

Greetings!
