### ISSUE TITLE
PortScanner issue

### ISSUE THREAD

**Issue by KevinOtten** [chrizator/netattack2#12]
Whenever I wan't to scan the network for hosts or kick someone off my network I get this:

Traceback (most recent call last):
  File "./netattack2.py", line 579, in <module>
    main()
  File "./netattack2.py", line 576, in main
    handle_option(option)
  File "./netattack2.py", line 80, in handle_option
    host_scan(False)
  File "./netattack2.py", line 214, in host_scan
    hostscan.do_scan(ip_range)
  File "/root/netattack2/src/scan.py", line 43, in do_scan
    nm = nmap.PortScanner()
AttributeError: 'module' object has no attribute 'PortScanner'

I already tried editing the file but nothing helped...
If someone had this as well and knows how to solve it, please let me know.

**Comment by KevinOtten** [comment]
Never mind, it was a python-nmap issue.......

**Comment by Colintur2004** [comment]
What eventually fixed this issue? I’m having the same thing. What did you do to fix it? Thanks

**Comment by KevinOtten** [comment]
> What eventually fixed this issue? I’m having the same thing. What did you do to fix it? Thanks

I don't remember precisely but I think I just reinstalled Python or Python-nmap. Try to reinstall both.
