### ISSUE TITLE
Please Install All Requirements

### ISSUE THREAD

**Issue by JaimePolo** [chrizator/netattack2#2]
Netattack works ok, however version 2 is asking to install all requirements, even when all of them are installed.

**Comment by enesilhaydin** [comment]
@JaimePolo try apt-get install python-nmap

**Comment by chrizator** [comment]
@JaimePolo Definitly try what enesilhaydin mentioned. If it still not works:
pip install scapy
pip install argparse

This is basically all you need. Next time, read the README.md :)
Greetings!
