### ISSUE TITLE
python-nfqeue

### ISSUE THREAD

**Issue by ImLilDev** [chrizator/netattack2#20]
On a frensh install of kali I got this :
unable to locate package python-nfqeue

Even the apt-get can’t fix this ! 
Someone have a similar issue and can help me ?

**Comment by ImLilDev** [comment]
Anyway got it fixed, that was easy lol 😂

**Comment by JeSuisRusse** [comment]
How did you fix the error ?

**Comment by joebo1** [comment]
I have the same problem. Can you post the solution? I'm lost.

Thank you very much!

**Comment by ImLilDev** [comment]
Just go to python file ! And remove every line when you see python nfqeue
(3 line in total)
Then rely the installation !
This will work without it !

**Comment by joebo1** [comment]
That's the solution! Thank you, SirCthulhu!

But, does the program work well without this package?

**Comment by ImLilDev** [comment]
I haven’t tested everything, but basic fonctionalities works fine ! So I presume that all the programs work fine ! 😅

**Comment by joebo1** [comment]
:laughing:    Thanks, SirCthulhu!

**Comment by rosleejasmin** [comment]
help me.. i have same problem.... python file location pleasseee

**Comment by Amo95** [comment]
@SirCthulhu  which python file are talking about here... Linux is filled with bunch of python scripts

I need your help please?

**Comment by Amo95** [comment]
well i've figured it out.. its the netattack2.py file i guess..
Any thanks for the contributions, it fixed mine perhaps partially

**Comment by ImLilDev** [comment]
I’m talking about the main file nettack2.py

Remove those 3 line with python nf and you guys will be good to go !

**Comment by x3l51** [comment]
Instead of `import nfqueue` you write `import netfilterqueue`

You can't use python3. Use this instead `sudo python2 netattack2.py`

You can alternatively look at my repos for I have made an fork that works with python3. It needs testing anyway.

**Comment by seebeerr23** [comment]
how to locate the python files ? i'm new in this so please help

**Comment by ImLilDev** [comment]
The file is simply called netattack2.py

But to be honest this tools doesn’t seems to be working in 2019. Wait for an update or find an similar tool.

**Comment by purecharcool** [comment]
what are those three lines?

**Comment by joebo1** [comment]
Now, I use AIRGEDDON for deauth attaks. In the option 4, you can select aircrack or MDK4. And it have channel hopping!

Luck!
