### ISSUE TITLE
Requirements installed. but still not working !

### ISSUE THREAD

**Issue by b3rt1ng** [chrizator/netattack2#23]
When i launch netattack2, it ask me to install the requirements:
[*] Installing requirements, please stand by...
Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages
E: Impossible d'obtenir le verrou /var/lib/dpkg/lock - open (11: Ressource temporairement non disponible)
E: Impossible de verrouiller le répertoire d'administration (/var/lib/dpkg/). Il est possible qu'un autre processus l'utilise.
E: Impossible d'obtenir le verrou /var/lib/dpkg/lock - open (11: Ressource temporairement non disponible)
E: Impossible de verrouiller le répertoire d'administration (/var/lib/dpkg/). Il est possible qu'un autre processus l'utilise.
E: Impossible d'obtenir le verrou /var/lib/dpkg/lock - open (11: Ressource temporairement non disponible)
E: Impossible de verrouiller le répertoire d'administration (/var/lib/dpkg/). Il est possible qu'un autre processus l'utilise.
E: Impossible d'obtenir le verrou /var/lib/dpkg/lock - open (11: Ressource temporairement non disponible)
E: Impossible de verrouiller le répertoire d'administration (/var/lib/dpkg/). Il est possible qu'un autre processus l'utilise.

[+] Requirements installed.
so here it looks like i can't find the ressources, i need to make netattack work proprely.
i result to this using the command "python2 netattack2.py"

using "./netattack2" i juste have:
ERROR: Modules missing.
Do you want to automatically install all requirements? (y/n): y
[*] Installing requirements, please stand by...
Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages
E: Impossible de trouver le paquet python-nfqueue

[+] Requirements installed.

but i still can't use netattack

i installed manually the requierments but it seem that they are not founded.

**Comment by Mikewins1** [comment]
Same problem  Anyone going to answer

**Comment by roronoaabdo** [comment]
same problem

**Comment by ajxdadev** [comment]
solved this problem !!
just check whether its installed properly or not 
 sudo apt-get remove --auto-remove python-netifaces 
then run this command 
$ sudo apt-get install python-netifaces 

It will work even if it shows you "Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages"  earlier
