### ISSUE TITLE
Do you want to automatically install all requirements?

### ISSUE THREAD

**Issue by ghost** [chrizator/netattack2#36]
sudo python2 netattack2.py                                                                                                  
ERROR: Modules missing.
Do you want to automatically install all requirements? (y/n): y
[*] Installing requirements, please stand by...
Requirement already satisfied: netifaces in /usr/lib/python3/dist-packages (0.11.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv                                   
E: Package 'python-scapy' has no installation candidate                                                                         
E: Unable to locate package python-nmap
E: Unable to locate package python-nfqueue

[+] Requirements installed.

reinstalling netattack2 didn't help.

**Comment by Pavis0247** [comment]
Did you find a solution?
