### ISSUE TITLE
NameError: global name 'utils' is not defined

### ISSUE THREAD

**Issue by usama7628674** [chrizator/netattack2#4]
[root@parrot]─[~/Desktop/netattack2]
└──╼ #./netattack2.py

    O       O    O O O O   O O O O O         O        O O O O O   O O O O O         O         O O O O O    O       O
    O O     O    O             O            O O           O           O            O O        O            O     O 
    O  O    O    O             O           O   O          O           O           O   O       O            O   O
    O   O   O    O O O O       O          O     O         O           O          O     O      O            O O
    O    O  O    O             O         O O O O O        O           O         O O O O O     O            O   O
    O     O O    O             O        O         O       O           O        O         O    O            O     O
    O       O    O O O O       O       O           O      O           O       O           O   O O O O O    O       O

                                        D I S C O V E R   W H A T 'S   P O S S I B L E
                                                     b y   c h r i z a t o r

    -----------
    | S C A N |
    -----------

      (1) Scan for Access-Points
      (2) Scan for hosts in your network

    ---------------
    | A T T A C K |
    ---------------

      DEAUTH
        (3) Deauth ONE network
        (4) Deauth MULTIPLE networks

        (5) Deauth ALL networks in your area

      KICK
        (6) Kick ONE user off your network
        (7) Kick MULTIPLE users off your network

        (8) Kick ALL users off your network (except you)

    (9) EXIT

    #> 8
Traceback (most recent call last):
  File "./netattack2.py", line 829, in <module>
    handle_choice()
  File "./netattack2.py", line 126, in handle_choice
    kick_all()
  File "./netattack2.py", line 812, in kick_all
    kick_hosts = host_scan(True, True, False, True)
  File "./netattack2.py", line 366, in host_scan
    ip_range = get_ip_range()
  File "./netattack2.py", line 311, in get_ip_range
    sub = utils.ltoa(net)
NameError: global name 'utils' is not defined

**Comment by chrizator** [comment]
utils comes from python-scapy. Make sure to install scapy!
`pip install scapy` or `apt-get install python-scapy`
