### ISSUE TITLE
when start netattack2 in terminal by this command ./netattack2

### ISSUE THREAD

**Issue by PawanBhusal** [chrizator/netattack2#6]
the error are as follow 
code@code-hack:~/Desktop/hacking/netattack2$ ./netattack2.py 
from: can't read /var/mail/threading
from: can't read /var/mail/time
./netattack2.py: line 10: syntax error near unexpected token `"scapy.runtime"'
./netattack2.py: line 10: `logging.getLogger("scapy.runtime").setLevel(logging.ERROR) # scapy, please shut up..'

**Comment by chrizator** [comment]
Somehow the shebang was not added to the netattack2.py file.
Download the repo again and try it out, should work fine now.

Thanks for reporting.
