### ISSUE TITLE
ValueError: Single '}' encountered in format string

### ISSUE THREAD

**Issue by Jay78** [chrizator/netattack2#7]
python netattack2.py
ERROR: Modules missing.
Do you want to automatically install all requirements? (y/n): y
Traceback (most recent call last):
  File "netattack2.py", line 48, in <module>
    auto_installer()
  File "netattack2.py", line 30, in auto_installer
    print("{{Y}*{N}} Installing requirements, please stand by...".format(Y=YELLOW, N=NORMAL))
ValueError: Single '}' encountered in format string

---> This was i get when i try to launch netattack2 :(

**Comment by chrizator** [comment]
Hello,
should be fixed now.

Thank you for reporting!

**Comment by Jay78** [comment]
python netattack2.py 
ERROR: Modules missing.
Do you want to automatically install all requirements? (y/n): y
[*] Installing requirements, please stand by...
Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 

[+] Requirements installed.

Getting this when i try to launch with python netattack2.py
