### ISSUE TITLE
Multiples issues

### ISSUE THREAD

**Issue by Jay78** [chrizator/netattack2#8]
Choose the target(s) seperated by ',' (comma).
Type 'all' to choose everything listed.
#> ipad.home
ERROR: Invalid input.
#> 192.168.1.13
ERROR: Invalid input.
#> 4
Traceback (most recent call last):
  File "netattack2.py", line 578, in <module>
    main()
  File "netattack2.py", line 575, in main
    handle_option(option)
  File "netattack2.py", line 93, in handle_option
    arp_kick()
  File "netattack2.py", line 420, in arp_kick
    arpspoof = spoof.Spoof(targets, local_ip, gateway_ip, gateway_mac, interface)
AttributeError: 'module' object has no attribute 'Spoof'

**Comment by Jay78** [comment]
Traceback (most recent call last):
  File "netattack2.py", line 578, in <module>
    main()
  File "netattack2.py", line 575, in main
    handle_option(option)
  File "netattack2.py", line 85, in handle_option
    arp_spoof()
  File "netattack2.py", line 443, in arp_spoof
    printings.arp_spoof()
AttributeError: 'module' object has no attribute 'arp_spoof'

**Comment by Jay78** [comment]
:(

**Comment by chrizator** [comment]
It is fixed now. I don't know how this could happen, I'm sorry!

**Comment by Jay78** [comment]
For Deauth : 

[*] Searching for WiFi-Networks... (10 sec.)


An unexpected error occurred. Aborting...

**Comment by Jay78** [comment]
For Deauth : 

[*] Searching for WiFi-Networks... (10 sec.)

+ When i sniff the network i can't see my pc is it normal ?

thx


An unexpected error occurred. Aborting...

**Comment by chrizator** [comment]
I don't really know what causes the issue. The actual exception will be now printed to the screen. Could you download the updated version and send me the output again? Thank you!

I don't really know what you mean with: When I sniff the network I can't see my PC.
Hopefully the script doesn't make your computer fly away :)

**Comment by Jay78** [comment]
[*] Searching for WiFi-Networks... (10 sec.)


An unexpected error occurred: argument for 's' must be a string
 
----

And for my pc i don't know it's the same on ettercap when i scan hosts i can see ipad iphone but not my computer that i'm using

**Comment by Jay78** [comment]
[*] Searching for WiFi-Networks... (10 sec.)


An unexpected error occurred: argument for 's' must be a string

**Comment by chrizator** [comment]
It should be fixed now. Please have a look :)
